FROM ubuntu:18.04 as bootstrap

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    bash \
    bc \
    binutils \
    build-essential \
    bzip2 \
    cpio \
    g++ \
    gcc \
    git \
    gzip \
    locales \
    libncurses5-dev \
    libdevmapper-dev \
    libsystemd-dev \
    make \
    mercurial \
    whois \
    patch \
    perl \
    python \
    rsync \
    sed \
    tar \
    vim \ 
    unzip \
    wget \
    bison \
    flex \
    libssl-dev \
    libfdt-dev \
    gettext \
    texinfo


ENV BR2_VERSION=2011.11

WORKDIR /buildroot

RUN git clone --depth 1 --branch ${BR2_VERSION} git://git.buildroot.net/buildroot /buildroot

